title: 'Contao Developer Documentation'
theme: 'hugo-theme-learn'
params:
  themeVariant: 'contao'
  disableSearch: false
  editURL: "https://github.com/contao/docs/edit/master/exampleSite/content/"
  disableLanguageSwitch: true
  baseHref: '/dev'
outputs:
  home: ['HTML', 'JSON']
